### ISSUE TITLE
osx travis builds are failing

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-dev-recipes#104]
Looks like our [`osx` builds are failing](https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/279732226#L654-L657) :
```
Installing conda-forge::anaconda-client-1.6.5-py_0 requires a minimum conda version of 4.3.
+ /io/conda-build-all -vvv --python 27 --upload omnia --dev --force -- /io/appveyor.yml /io/conda-build-all /io/devtools /io/openmm /io/openmmforcefields /io/README.md
ImportError encountered:
No module named 'conda.utils'
```
I'm guessing that warning message means that [this fix](https://github.com/omnia-md/conda-recipes/pull/814/commits/cebe24c95d453adcc3633205b2ae6cc77b852248) will work here too.

**Comment by Lnaden** [comment]
I think this is resolved
