### ISSUE TITLE
Switch to building OpenMM with debug symbols

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-dev-recipes#115]
We should switch [this line](https://github.com/omnia-md/conda-dev-recipes/blob/master/openmm/build.sh#L6) to build OpenMM with debug symbols.

**Comment by jchodera** [comment]
cc: @pgrinaway

**Comment by jaimergp** [comment]
Do we want to add this in nightly builds?

**Comment by jchodera** [comment]
Yes, if possible!

**Comment by jaimergp** [comment]
Last commit includes `-g` in Linux if a scheduled/nightly build is being run.

**Comment by jaimergp** [comment]
Fixed a bug where the `NIGHTLY` variable wasn't being passed to the Docker build. Nightlies for Linux should include the symbols now.

**Comment by jchodera** [comment]
It's working!
https://anaconda.org/omnia-dev/openmm/files
![image](https://user-images.githubusercontent.com/3656088/72671688-d9ffff80-3a02-11ea-9f2f-bb13768c94c4.png)

**Comment by jaimergp** [comment]
Yes! Let's see if we get the debug symbols with the next nightly. These should be larger in size, like ~50MB.

**Comment by jaimergp** [comment]
Debug packages confirmed with last commit. Check the ~50MB sizes in Linux64:

![image](https://user-images.githubusercontent.com/2559438/72744302-94336a80-3bad-11ea-8bf5-f91071ad6c22.png)
