### ISSUE TITLE
Change source docker image to Omnia from Jchodera

### ISSUE THREAD

**Issue by Lnaden** [omnia-md/conda-dev-recipes#125]
We have been uploading and getting Docker images from @jchodera's Docker Hub profile, however, that is not tenable long term as we will want multiple admins to work on the docker containers going forward. 

To that end, @jchodera and I have created the Omnia MD organization on [Docker Hub](https://hub.docker.com/r/omniamd/omnia-linux-anvil/) (+ [Docker Cloud](https://cloud.docker.com/swarm/omniamd/repository/docker/omniamd/omnia-linux-anvil/general) so multiple people can be admins and control the builds in the future. 

We will eventually need to change the [`.travis.yml` line](https://github.com/omnia-md/conda-dev-recipes/blob/master/.travis.yml#L59) from  `jchodera/omnia-linux-anvil:{tag}` to `omniamd/omnia-linux-anvil:{tag}`. Right now both accounts are building the same tags starting with `cuda91` as we are debugging the new image and the migration, so this is an "eventually" action.

**Comment by Lnaden** [comment]
#180 is now using stuff from @jaimergp but I still think we should use images from the central omniamd Docker Cloud

**Comment by jaimergp** [comment]
Agree. I only used my account because I couldn't create a repo in @omnia-md. Which reminds, can you give me access to the GH org? Thank you!

**Comment by Lnaden** [comment]
Did you mean in the Docker org?

**Comment by jaimergp** [comment]
I just received invitations to both the Docker and Github orgs, but I can't fork to @omnia-md. 

![image](https://user-images.githubusercontent.com/2559438/72356013-ca25aa00-36e8-11ea-95b7-21bef4ac5d23.png)

**Comment by Lnaden** [comment]
Right, once you are in the org, I'll give you permissions. Why do you need another repo? Why can't we just use https://github.com/omnia-md/omnia-linux-anvil ?

**Comment by Lnaden** [comment]
You have permissions to the Omnia-MD Github and the omniamd docker org as well

**Comment by jaimergp** [comment]
> Why can't we just use https://github.com/omnia-md/omnia-linux-anvil ?

I forked the CF docker-images repo for simplicity. They have the CI setup for automatic uploading and everything, so it was only a matter of adding more CUDA versions to the build matrix.

**Comment by Lnaden** [comment]
Got it. I'd like to get them on the Omniamd Docker org eventually if you can, that way we're not relying on someone's personal account (although I think that's what you are working towards). Feel free to make a new image name + tags if you want too, so you don't have to use the omnia-linux-anvil name.

**Comment by jaimergp** [comment]
Yep, working on that as we speak!

**Comment by jaimergp** [comment]
Addressed with commit 3bf8761
