### ISSUE TITLE
Uploads are broken

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-dev-recipes#176]
@peastman: Just wanted to point out that @j-wags noticed that omnia builds are broken again, with the last successful upload being 12 days ago.

I note that the last successful `omnia-dev` nightly upload of `openmm` was 24 days ago:
https://anaconda.org/omnia-dev/openmm/files

Did you fix anything to get builds working again for https://github.com/omnia-md/conda-recipes-cuda? If so, could you make those changes here too?

**Comment by j-wags** [comment]
That's... strange, since OFFTK uploaded successfully 12 days ago https://travis-ci.org/omnia-md/conda-recipes/builds/611613761

And actually, openmm uploaded successfully _4_ days ago https://anaconda.org/omnia/openmm

**Comment by peastman** [comment]
I have a PR open to try to fix the dev builds (#175).  If you have any insight on the failures reported there, that would be a big help.

**Comment by jaimergp** [comment]
Fixed with #182

**Comment by jchodera** [comment]
Woohoo! Huge thanks, @jaimergp!
