### ISSUE TITLE
Remove Appveyor/windows

### ISSUE THREAD

**Issue by rmcgibbo** [omnia-md/conda-dev-recipes#3]
Unless you can figure out a way to have the windows builds also triggered on a crontab, I'm not sure they're really useful here.

**Comment by jchodera** [comment]
Maybe scheduled builds?

https://www.appveyor.com/docs/build-configuration#scheduled-builds

**Comment by jchodera** [comment]
I've scheduled appveyor builds for 0h and 12h UTC.

**Comment by jchodera** [comment]
(This has to be done through the UI, under the Settings > General tab)
