### ISSUE TITLE
Some Notes and Suggestions

### ISSUE THREAD

**Issue by rmcgibbo** [omnia-md/conda-dev-recipes#4]
1. I don't think this is working properly w.r.t rebuilding packages, once the first version has been uploaded to Anaconda.org: https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/101268814. It's just skipping them and not building anything, since it sees the version numbers match on. You probably don't want to pass the `--check-against omnia` flag: https://github.com/omnia-md/conda-dev-recipes/blob/master/.travis.yml#L53-L55
2. The files `post-build.{sh,bat}` should be removed from https://github.com/omnia-md/conda-dev-recipes/tree/master/openmm-dev. They were a holdover from a previous version of conda or OpenMM or something. They haven't been necessary since OpenMM 6.2 I think, and aren't in the omnia-md/conda-recipes version.
3. You might want to change the repo such that the `conda-build-all` script isn't duplicated between the two repos. Unfortunately they've already gotten out of sync, and it'll only get worse. 
   - The simplest thing might just be for this repo to `wget` the script from `https://raw.githubusercontent.com/omnia-md/conda-recipes/master/conda-build-all`.
   - The more proper solution would be to package that script up as a conda package itself, and give it a version number / repo / recipe etc
   - Or switch to using https://github.com/scitools/conda-build-all, since someone else is maintaining that.
4. If other recipes start to go in here beyond `openmm-dev`, it will become useful to have something like a maintainer field (https://github.com/conda/conda-build/issues/670) in the conda recipe so that the appropriate person could be emailed if the package fails to build from source, or some fancy github-api-fu so that an issue could be automatically created on the github repo for the project (https://developer.github.com/v3/issues/#create-an-issue).

**Comment by jchodera** [comment]
Thanks for the great ideas!  Apologies for not getting to this earlier, but tackling these now.

(Also, feel free to create PRs or fix things as needed!  I think you have full repo rights.)

**Comment by jchodera** [comment]
> You might want to change the repo such that the conda-build-all script isn't duplicated between the two repos.

Great idea.  I'll just add a `--force-upload` flag to ensure that the anaconda.org package is replaced---this was the only reason for the duplication.

**Comment by jchodera** [comment]
See https://github.com/omnia-md/conda-recipes/pull/418

**Comment by rmcgibbo** [comment]
It would be nice if the -dev package conflicted with the non -dev package so that the installer wouldn't let you try to simultaneously have both installed in the same enviroment, but it looks like conda doesn't support that https://github.com/conda/conda/issues/608

**Comment by jchodera** [comment]
Yep.  Pinged that thread.

**Comment by jchodera** [comment]
I've hopefully addressed most of these issues in https://github.com/omnia-md/conda-dev-recipes/pull/32

**Comment by jchodera** [comment]
Unfortunately, using package numbers of 0.0.0 forces conflicts or uninstallation of packages that require a minimum `openmm` version, e.g. 

```
[chodera@mskcc-ln1 ~]$ conda install --yes -c https://conda.anaconda.org/omnia/label/dev openmm==0.0.0
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata ...........
Solving package specifications: ....

The following specifications were found to be in conflict:
  - alchemy -> openmm >=6.3
  - alchemy -> python 3.4*|3.5*
  - openmm ==0.0.0
Use "conda info <package>" to see the dependencies for each package.
```

What do we think about using the _new_ version number, but leaving the package on the `dev` label?

**Comment by jchodera** [comment]
It doesn't appear that any combination of arguments to `conda install` will allow me to force-install `openmm` 0.0.0

**Comment by jchodera** [comment]
OK, I have `openmm 7.1.0` on anaconda cloud right now, and I've confirmed that 

``` bash
conda install --yes openmm
```

gives the latest release version, `openmm 7.0.1`, unless you use the `dev` label channel:

``` bash
conda install --yes -c https://conda.anaconda.org/omnia/label/dev openmm
```

https://anaconda.org/omnia/openmm/files
