### ISSUE TITLE
git revision

### ISSUE THREAD

**Issue by rmcgibbo** [omnia-md/conda-dev-recipes#8]
It would be nice if this worked:

```
$ python -c 'import simtk.openmm as mm; print(mm.version.git_revision)'
Unknown
```

I think this would require, for one, switching back to downloading the package from git instead of from zip in the meta.yml, or that feature just might be broken in the openmm cmake scripts.

**Comment by jchodera** [comment]
Sure.

#9

**Comment by jchodera** [comment]
Whoops.  Close if #9 solves this.

**Comment by rmcgibbo** [comment]
```
$ python -c 'import simtk.openmm as mm; print(mm.version.git_revision)'
a5d900d1e5f63c5bddce72b6c2deb79c150ef008
```
